version: "1.0.0"

services:
  app:
    build: .
    container_name: penezi_docker
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
